# ModelMuxer (c) 2025 Ajay Rajput
# Licensed under Business Source License 1.1 – see LICENSE for details.

# Gitleaks configuration for ModelMuxer
# Focused approach to prevent false positives in documentation while maintaining security

title = "ModelMuxer Gitleaks Configuration"

# Global allowlist - most effective approach
[allowlist]
description = "Comprehensive allowlist for documentation and test files"

# File paths to completely ignore
paths = [
    '''docs/.*''',     # All documentation files
    '''README\.md''',  # README file
    '''tests/.*''',    # All test files
    '''examples/.*''', # Example files
    '''\.github/.*''', # GitHub workflows and configs
]

# Regex patterns to ignore across all files
regexes = [
    # Authorization headers in documentation
    '''curl.*Authorization.*REDACTED''',
    '''curl.*Authorization.*\*\*\*''',
    '''curl.*Authorization.*example''',
    '''curl.*Authorization.*<.*>''',
    '''curl.*Authorization.*test''',
    '''curl.*Authorization.*fake''',
    '''curl.*Authorization.*demo''',
    '''curl.*Authorization.*placeholder''',
    '''curl.*Authorization.*sample''',

    # Bearer tokens in documentation
    '''Bearer <.*>''',
    '''Bearer test-.*''',
    '''Bearer fake-.*''',
    '''Bearer example-.*''',
    '''Bearer demo-.*''',
    '''Bearer placeholder-.*''',
    '''Bearer sample-.*''',

    # API keys in documentation
    '''api[_-]?key.*test''',
    '''api[_-]?key.*fake''',
    '''api[_-]?key.*example''',
    '''api[_-]?key.*<.*>''',
    '''api[_-]?key.*placeholder''',
    '''api[_-]?key.*sample''',
    '''api[_-]?key.*demo''',

    # Generic placeholders
    '''<[^>]*>''',      # HTML-style placeholders
    '''\$\{[^}]*\}''',  # Environment variable placeholders
    '''your-.*-here''', # Template placeholders
    '''.*-NOT-REAL''',  # Clearly fake values
    '''.*-FAKE''',      # Fake indicators
    '''.*-for-ci''',    # CI test values

    # Specific problematic patterns
    '''\*\*\*;3;mREDACTED''',       # The specific pattern from the error
    '''Authorization.*mREDACTED''',
]

# Stop words that indicate non-secrets
stopwords = [
    "example",
    "test",
    "fake",
    "demo",
    "sample",
    "placeholder",
    "template",
    "redacted",
    "masked",
    "hidden",
    "not-real",
    "ci-testing",
]
