# ModelMuxer (c) 2025 Ajay Rajput
# Licensed under Business Source License 1.1 – see LICENSE for details.
# Markdownlint configuration for ModelMuxer documentation
# This file configures which markdown rules to enforce

# MD013: Line length rule - increase limit for technical documentation
MD013:
  line_length: 400
  heading_line_length: 400
  code_block_line_length: false
  code_blocks: false
  tables: false
  headings: true
  headers: true

# MD029: Ordered list item prefix - allow both styles
MD029: false

# MD024: Multiple headings with the same content - allow in different sections
MD024:
  siblings_only: true

# MD033: Inline HTML - allow for complex documentation
MD033: false

# MD034: Bare URL - allow in certain contexts
MD034: false

# Disable problematic rules for technical documentation
MD041: false # First line in file should be a top level heading
MD040: false # Fenced code blocks should have a language specified
MD031: false # Fenced code blocks should be surrounded by blank lines
MD051: false # Link fragments should be valid
MD022: false # Headings should be surrounded by blank lines
MD032: false # Lists should be surrounded by blank lines
